server:
  port: 8686
  servlet:
    context-path: /yang
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://8.131.71.173:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    name: root
    password: feng
  redis:
    host: 8.131.71.173
    port: 6379
    password: feng
    timeout: 5000
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    #连接池中的最大空闲连接
        min-idle: 0    #连接池中的最小空闲连接
